### 1a) calculate dot product manually

#### First let's examine how it is calculated by numpy

In [2]:
import numpy as np
import pandas as pd

v = np.arange(3) # let's just get any arbitrary array
u = v.T
np.dot(v,v) # well, this seems to work 'properly' 

5

In [3]:
type(u)

numpy.ndarray

In [4]:
v.shape

(3,)

In [5]:
u.shape # hm, has the same shape after transposing, should not it be (, 5)?

(3,)

In [6]:
np.dot(u, v) # not too surprisingly, gives the same result

5

#### Let's try to define something that would calculate the dot product

In [7]:
def dot_product(u, v):
    result = 0
    try:
        if not (u.shape == v.shape and u.ndim == 1):
            raise ValueError('Your vectors are of not proper dimensions!')
    except ValueError as ve:
        print(ve)
    else:
        for i in range(len(u)):
            result += u[i]*v[i]
        return result
            
    

In [8]:
dot_product(u,v)

5

### 1b) calculate cross product manually

In [9]:
def cross_product(u, v):
    a = [u, v]
    result = np.array([0,0,0])
    for i, s in enumerate(a):
        if len(a[i]) == 2:
            a[i] = np.append(a[i], 0)
        else:
            pass
    try:
        if not (a[0].shape == a[1].shape and len(a[0]) == 3):
            raise ValueError('Your vectors are of not proper dimensions!')
    except ValueError as ve:
        print(ve)
    else:
        for i in range(len(a[0])):
            result[i] += a[0][i-2]*a[1][i-1] - a[0][i-1]*a[1][i-2]
        return result

In [10]:
cross_product(u,v)

array([0, 0, 0])

In [11]:
g = np.array([1, 3, 9])
k = np.array([9, 3, 1])

In [12]:
cross_product(g, k)

array([-24,  80, -24])

In [13]:
res = np.cross(g, k) # good this seems to be working

In [14]:
print(res)

[-24  80 -24]


In [15]:
p = np.array([1, 3])
t = np.array([9, 3])

In [16]:
cross_product(p,t) # OK, good

array([  0,   0, -24])

### One Hot Encoding

#### One hot encoding is a method to give categorical data numerical values so that machine learning algorithms could handle them, withouth, but withouth implying ordinal relationships. To achieve this, instead of simpel numerical values, binary variables are employed. Not sure how to explain in computer science terms, but for me it looks like n unique categories can be represented as eigenvectors of an n dimensional space.

In [17]:
belize = pd.read_csv('belize_airbnb_listings.csv')
belize_neighb = belize['neighbourhood_group'].to_frame()
belize_neighb['neighbourhood_group'].unique()

array(['Belize', 'Stann Creek', 'Toledo', 'Cayo', 'Corozal',
       'Orange Walk'], dtype=object)

In [18]:
conditions = [belize_neighb['neighbourhood_group'] == 'Belize', belize_neighb['neighbourhood_group'] == 'Stann Creek', 
              belize_neighb['neighbourhood_group'] == 'Toledo', belize_neighb['neighbourhood_group'] == 'Cayo', 
              belize_neighb['neighbourhood_group'] == 'Corozal', belize_neighb['neighbourhood_group'] == 'Orange Walk']
outputs =  [[1,0,0,0,0,0], [0,1,0,0,0,0], [0,0,1,0,0,0], [0,0,0,1,0,0], [0,0,0,0,1,0], [0,0,0,0,0,1]]

In [19]:
#belize_neighb[belize_neighb['neighbourhood_group'] == 'Belize'] = np.array([1,0,0,0,0,0]) # this fails miserably, time to give up

In [20]:
pd.get_dummies(belize_neighb['neighbourhood_group']).head(3) # this does not look like what I described: maybe my understanding is not correct... nevertheless, maybe let's try to reproduce this manually

Belize  Cayo  Corozal  Orange Walk  Stann Creek  Toledo
0       1     0        0            0            0       0
1       1     0        0            0            0       0
2       1     0        0            0            0       0

In [21]:
belize_neighb['Belize'] = np.nan
belize_neighb['Stann Creek'] = np.nan
belize_neighb['Toledo'] = np.nan
belize_neighb['Cayo'] = np.nan
belize_neighb['Corozal'] = np.nan
belize_neighb['Orange Walk'] = np.nan

belize_neighb.loc[belize_neighb['neighbourhood_group'] == 'Belize', 'Belize'] = 1
belize_neighb['Belize'].fillna(value = 0, inplace = True)

belize_neighb.loc[belize_neighb['neighbourhood_group'] == 'Stann Creek', 'Stann Creek'] = 1
belize_neighb['Stann Creek'].fillna(value = 0, inplace = True)

belize_neighb.loc[belize_neighb['neighbourhood_group'] == 'Toledo', 'Toledo'] = 1
belize_neighb['Toledo'].fillna(value = 0, inplace = True)

belize_neighb.loc[belize_neighb['neighbourhood_group'] == 'Cayo', 'Cayo'] = 1
belize_neighb['Cayo'].fillna(value = 0, inplace = True)

belize_neighb.loc[belize_neighb['neighbourhood_group'] == 'Corozal', 'Corozal'] = 1
belize_neighb['Corozal'].fillna(value = 0, inplace = True)

belize_neighb.loc[belize_neighb['neighbourhood_group'] == 'Orange Walk', 'Orange Walk'] = 1
belize_neighb['Orange Walk'].fillna(value = 0, inplace = True)

In [22]:
belize_neighb

neighbourhood_group  Belize  Stann Creek  Toledo  Cayo  Corozal  \
0                 Belize     1.0          0.0     0.0   0.0      0.0   
1                 Belize     1.0          0.0     0.0   0.0      0.0   
2                 Belize     1.0          0.0     0.0   0.0      0.0   
3            Stann Creek     0.0          1.0     0.0   0.0      0.0   
4                 Belize     1.0          0.0     0.0   0.0      0.0   
...                  ...     ...          ...     ...   ...      ...   
2791              Belize     1.0          0.0     0.0   0.0      0.0   
2792             Corozal     0.0          0.0     0.0   0.0      1.0   
2793              Belize     1.0          0.0     0.0   0.0      0.0   
2794              Belize     1.0          0.0     0.0   0.0      0.0   
2795                Cayo     0.0          0.0     0.0   1.0      0.0   

      Orange Walk  
0             0.0  
1             0.0  
2             0.0  
3             0.0  
4             0.0  
...           ...  
2791          0.0  
2792          0.0  
2793          0.0  
2794          0.0  
2795          0.0  

[2796 rows x 7 columns]