### Homework 3 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into an numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [3]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


1. How can you get help on `np.array`?

Call `dir()` on `np.array`. 

Call `dir()` on `car`.

Note the difference. `car` has methods and attributes we can use.

In [4]:
help(np.array)


Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [5]:
dir(np.array)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [6]:
dir(car)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

2. What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [7]:
print(car.dtype)
print(mpg.dtype)

object
float64


In [8]:
print(horsepower.dtype)
print(origin.dtype)

float64
object


3. `numpy` is often imported as `np`. What is this action called? Why might you do this? 

It is aliasing and it makes a code simpler to put together as lenghty names can be referred by their aliases.

4. Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [9]:
print(car.ndim)
print(mpg.ndim)
print(cylinders.ndim)
print(displacement.ndim)
print(horsepower.ndim)
print(weight.ndim)
print(acceleration.ndim)
print(model.ndim)
print(origin.ndim)

1
1
1
1
1
1
1
1
1


Looks like all of them have only 1 dimension...

5. Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [10]:
#print(mpg)
#print(mpg*12)
#print(mpg/3)
#print(mpg**4)
print(mpg**0.5)

[4.24264069 3.87298335 4.24264069 4.         4.12310563 3.87298335
 3.74165739 3.74165739 3.74165739 3.87298335 0.         0.
 0.         0.         0.         3.87298335 3.74165739 0.
 3.87298335 3.74165739 4.89897949 4.69041576 4.24264069 4.58257569
 5.19615242 5.09901951 5.         4.89897949 5.         5.09901951
 4.58257569 3.16227766 3.16227766 3.31662479 3.         5.19615242
 5.29150262 5.         5.         0.         4.35889894 4.
 4.12310563 4.35889894 4.24264069 3.74165739 3.74165739 3.74165739
 3.74165739 3.46410162 3.60555128 3.60555128 4.24264069 4.69041576
 4.35889894 4.24264069 4.79583152 5.29150262 5.47722558 5.47722558
 5.56776436 5.91607978 5.19615242 5.09901951 4.89897949 5.
 4.79583152 4.47213595 4.58257569 3.60555128 3.74165739 3.87298335
 3.74165739 4.12310563 3.31662479 3.60555128 3.46410162 3.60555128
 4.35889894 3.87298335 3.60555128 3.60555128 3.74165739 4.24264069
 4.69041576 4.58257569 5.09901951 4.69041576 5.29150262 4.79583152
 5.29150262 5.19615242 3.60

6. What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [11]:
import statistics as st

operations = [sum, min, max, st.median, st.mode]
for i in operations:
    print(i(horsepower))

42033.0
0.0
230.0
93.5
150.0


7. Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [12]:
subset1 = acceleration[:6]
subset2 = acceleration[6:]

print(subset1)

[12.  11.5 11.  12.  10.5 10. ]


8. Show how to select the number `99` in the array below. 

In [13]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])

In [14]:
selected = select_99[1,2]
print(selected)

99


9. Select the last element in each subarray (do this with one operation.)

In [15]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])

selected_more = select_more[(0,1,2),(2,2,2)]
print(selected_more)
# returns array([3, 6, 9])

[3 6 9]


10. Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [16]:
#print(np.lookfor('log'))
print(np.log(mpg))

[2.89037176 2.7080502  2.89037176 2.77258872 2.83321334 2.7080502
 2.63905733 2.63905733 2.63905733 2.7080502        -inf       -inf
       -inf       -inf       -inf 2.7080502  2.63905733       -inf
 2.7080502  2.63905733 3.17805383 3.09104245 2.89037176 3.04452244
 3.29583687 3.25809654 3.21887582 3.17805383 3.21887582 3.25809654
 3.04452244 2.30258509 2.30258509 2.39789527 2.19722458 3.29583687
 3.33220451 3.21887582 3.21887582       -inf 2.94443898 2.77258872
 2.83321334 2.94443898 2.89037176 2.63905733 2.63905733 2.63905733
 2.63905733 2.48490665 2.56494936 2.56494936 2.89037176 3.09104245
 2.94443898 2.89037176 3.13549422 3.33220451 3.40119738 3.40119738
 3.4339872  3.55534806 3.29583687 3.25809654 3.17805383 3.21887582
 3.13549422 2.99573227 3.04452244 2.56494936 2.63905733 2.7080502
 2.63905733 2.83321334 2.39789527 2.56494936 2.48490665 2.56494936
 2.94443898 2.7080502  2.56494936 2.56494936 2.63905733 2.89037176
 3.09104245 3.04452244 3.25809654 3.09104245 3.33220451 3.135494

C:\Users\BALAZS~1.VAR\AppData\Local\Temp/ipykernel_7584/452171526.py:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(mpg))


11. You your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [17]:
#type(origin)
origin_test = [0,6,5,0,6,5]
uniques = np.unique(origin_test)
print(uniques)

[0 5 6]


12. 
- Create a 2D array and print its shape as well as ndim. (Any shape is fine)

- Create a 3D array and print its shape as well as ndim.

- Create a 4D array and print its shape as well as ndim. *It's hard to visualize 4-Dimensions but numpy can do it with ease!*

In [18]:
a = np.array([[0,1],[1,0]])
print(a.ndim, a.shape)
b = np.array([[[1,0,0], [0,1,0], [0,0,1]]])
print(b.ndim, b.shape)
c = np.array([[[1,0,0], [0,1,0], [0,0,1]]], ndmin = 4)
print(c.ndim, c.shape)

2 (2, 2)
3 (1, 3, 3)
4 (1, 1, 3, 3)


13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [26]:
z = np.array(df.Origin == 'US')
print(z)
print(type(([df.Origin == 'US'])))

[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True False  True  True  True
 False False False False False False  True  True  True  True  True False
  True False  True False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False False False
 False False False  True False  True False  True  True  True  True  True
  True  True  True  True  True  True False  True  True  True  True False
 False False False  True False False  True False  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True  True False  True False False  True
  True False  True  True False False False False  True False False  True
  True  True  True  True False  True False  True  True  True  True  True
  True  True  True  True False False False False False  True False False
 False False False  True  True  True  True  True  T

14. Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [28]:
USCAR = car[z]
print(USCAR)

['Chevrolet Chevelle Malibu' 'Buick Skylark 320' 'Plymouth Satellite'
 'AMC Rebel SST' 'Ford Torino' 'Ford Galaxie 500' 'Chevrolet Impala'
 'Plymouth Fury iii' 'Pontiac Catalina' 'AMC Ambassador DPL'
 'Chevrolet Chevelle Concours (sw)' 'Ford Torino (sw)'
 'Plymouth Satellite (sw)' 'AMC Rebel SST (sw)' 'Dodge Challenger SE'
 "Plymouth 'Cuda 340" 'Ford Mustang Boss 302' 'Chevrolet Monte Carlo'
 'Buick Estate Wagon (sw)' 'Plymouth Duster' 'AMC Hornet' 'Ford Maverick'
 'AMC Gremlin' 'Ford F250' 'Chevy C20' 'Dodge D200' 'Hi 1200D'
 'Chevrolet Vega 2300' 'Ford Pinto' 'AMC Gremlin'
 'Plymouth Satellite Custom' 'Chevrolet Chevelle Malibu' 'Ford Torino 500'
 'AMC Matador' 'Chevrolet Impala' 'Pontiac Catalina Brougham'
 'Ford Galaxie 500' 'Plymouth Fury iii' 'Dodge Monaco (sw)'
 'Ford Country Squire (sw)' 'Pontiac Safari (sw)'
 'AMC Hornet Sportabout (sw)' 'Chevrolet Vega (sw)' 'Pontiac Firebird'
 'Ford Mustang' 'Mercury Capri 2000' 'Plymouth Cricket'
 'Dodge Colt Hardtop' 'Chevrolet Vega' 'Ford

**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

1.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

In [29]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

2. Transpose the following array. 

In [33]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])


In [34]:
np.transpose(transpose_me)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

3. Why does this multiplication operation fail? 

In [ ]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2

Dimensions do not match

Use numpy to answer the following questions. 

4. What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

In [38]:
E = np.array(origin == 'Europe')
horsepower[E].mean()

78.78082191780823

5. On average are Japanse cars more fuel efficient than US cars? 

In [42]:
mpg[np.array(origin == 'US')].mean() < mpg[np.array(origin == 'Japan')].mean()

True

6. What is the correlation coefficient of `mpg` and `weight`? What is a correlaton coefficient?

In [43]:
np.corrcoef(mpg, weight)
#I really doubt this is we are looking for...

array([[ 1.        , -0.78750994],
       [-0.78750994,  1.        ]])

7. Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 

arrays consume less memory and elementwise operations take much less time (5-10 X) than using lists. Lists are still preferred if working with different kinds of datatypes.